name: Build and Deploy GitHub Pages with LFS

on:
  push:
    branches:
      - main  # Change this to your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v4
        with:
          lfs: true  # Ensures LFS files are included

      - name: Pull LFS files
        run: git lfs pull

      - name: Build Jekyll site (like GitHub Pages does)
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          future: false
          build_revision: ${{ github.sha }}
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload site artifact (like GitHub Pages does)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: github-pages
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
